In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
import xgboost as XGBClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.feature_selection import RFECV
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GridSearchCV

In [2]:
import time

params = {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}



dict_classifiers = {
    'Logistic Regression': LogisticRegression(solver='lbfgs', max_iter =5000),
    'Nearest Neighbors': GridSearchCV(KNeighborsClassifier(), params, cv=5),
    'Support Vector Machine': SVC(gamma = 'auto'),
    'Decision Tree': tree.DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(n_estimators=100),
    'Neural Net': MLPClassifier(solver='adam',alpha=0.0001,learning_rate='constant',learning_rate_init=0.001),
    'Naive Bayes': GaussianNB()
}

# Import and merge data

In [4]:
import os
import pandas as pd

# current directory csv files
csvs = [x for x in os.listdir('.') if x.endswith('.csv')]
# stats.csv -> stats
fns = [os.path.splitext(os.path.basename(x))[0] for x in csvs]

e = {}
for i in range(len(fns)):
    e[fns[i]] = pd.read_csv(csvs[i])

In [6]:
e['SH601088'].head(5)

,Unnamed: 0,volumelag,rsilag,fastKlag,fastDlag,ADlag,OBVlag,MA5lag,MA15lag,day5Returnlag,day15Returnlag,PROClag
0,Day17,14753200,41.546629,0.450712,0.393310,-0.444491,21737400,19.95222,19.925720,0.799956,-1.562416,-0.264021
1,Day18,13919000,36.468773,0.379940,0.445887,-0.889355,7818400,19.94956,19.893013,0.469101,-1.056378,-0.863668
2,Day19,9662200,43.858272,0.639970,0.490207,0.899698,17480600,20.00260,19.890360,0.532054,0.331809,0.863668
3,Day20,15533500,44.918806,0.629609,0.549839,-0.600000,33014100,20.02912,19.896547,-0.131836,1.067863,0.132097
4,Day21,19682600,44.023224,0.592598,0.620726,0.818099,13331500,20.01852,19.908920,0.000000,0.934443,-0.132097

In [7]:
tmp = [x for x in os.listdir('/Users/j/Desktop/2020 Spring/DSO 530/Project/raw data 17-19') if x.endswith('.csv')]
a = '/Users/j/Desktop/2020 Spring/DSO 530/Project/raw data 17-19/'
csvs = []
for i in tmp:
    csvs.append(a + i)

In [8]:

# stats.csv -> stats
fns = [os.path.splitext(os.path.basename(x))[0] for x in csvs]

r = {}
for i in range(len(fns)):
    r[fns[i]] = pd.read_csv(csvs[i])

In [10]:
r['SH601088'].head(5)

   Time     Open     High      Low    Close    Volume
0  Day1  20.6178  21.0554  20.2598  20.2864  46916400
1  Day2  20.3924  20.4720  20.1538  20.3659  17406600
2  Day3  20.2864  20.5648  19.9947  20.0875  29612700
3  Day4  20.0742  20.1405  19.8090  19.9814  23158200
4  Day5  19.9549  20.0477  19.8488  19.8621  10172600

In [11]:
col = ['Time', 'volumelag', 'rsilag', 'fastKlag', 'fastDlag', 'ADlag',
       'OBVlag', 'MA5lag', 'MA15lag', 'day5Returnlag', 'day15Returnlag',
       'PROClag']

In [13]:
for i in fns:
    e[i].columns = col

In [14]:
e['SH601088'].head(5)

,Time,volumelag,rsilag,fastKlag,fastDlag,ADlag,OBVlag,MA5lag,MA15lag,day5Returnlag,day15Returnlag,PROClag
0,Day17,14753200,41.546629,0.450712,0.393310,-0.444491,21737400,19.95222,19.925720,0.799956,-1.562416,-0.264021
1,Day18,13919000,36.468773,0.379940,0.445887,-0.889355,7818400,19.94956,19.893013,0.469101,-1.056378,-0.863668
2,Day19,9662200,43.858272,0.639970,0.490207,0.899698,17480600,20.00260,19.890360,0.532054,0.331809,0.863668
3,Day20,15533500,44.918806,0.629609,0.549839,-0.600000,33014100,20.02912,19.896547,-0.131836,1.067863,0.132097
4,Day21,19682600,44.023224,0.592598,0.620726,0.818099,13331500,20.01852,19.908920,0.000000,0.934443,-0.132097

In [15]:
c = {}
for i in fns:
    c[i] = r[i][['Time','Open','Close']].merge(e[i],how='left',on='Time')

In [22]:
trntst = {}

for i in fns:
    trntst[i] = c[i][:504]

In [16]:
df_test = c['SH601088']

In [17]:
df_test

,Time,Open,Close,volumelag,rsilag,fastKlag,fastDlag,ADlag,OBVlag,MA5lag,MA15lag,day5Returnlag,day15Returnlag,PROClag
0,Day1,20.6178,20.2864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Day2,20.3924,20.3659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Day3,20.2864,20.0875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Day4,20.0742,19.9814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Day5,19.9549,19.8621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Day752,29.7170,29.8009,27239472.0,55.554178,0.749984,0.680560,0.636216,1.771986e+09,29.39168,29.090940,2.546318,2.963086,0.849919
752,Day753,29.7338,29.2978,35167648.0,56.693146,0.802100,0.715283,0.110964,1.807154e+09,29.55604,29.153547,2.185258,2.776255,0.281932
753,Day754,29.3313,29.5493,34585208.0,48.643407,0.489596,0.680560,-0.870744,1.772568e+09,29.58288,29.173673,-1.131839,0.517722,-1.702617
754,Day755,29.3816,29.4319,19086854.0,52.290326,0.645817,0.645837,0.699553,1.791655e+09,29.56610,29.200500,0.284400,2.561139,0.854763
755,Day756,29.3649,29.6667,19094004.0,50.488002,0.523228,0.552880,-0.000373,1.772561e+09,29.55938,29.241867,-0.959384,2.272577,-0.398093

# Define the y label

In [ ]:
# Calculating the price change percentage over the past 1/2/3/4/5 days.
# Assigning label 1 or 0 to each feature.

In [21]:
df_test['percentage 1 day'] = np.zeros(756)
df_test['percentage 2 day'] = np.zeros(756)
df_test['percentage 3 day'] = np.zeros(756)
df_test['percentage 4 day'] = np.zeros(756)
df_test['percentage 5 day'] = np.zeros(756)

In [22]:
for i in range(0,755):
    df_test.loc[i,'percentage 1 day'] = (df_test.loc[i+1,'Close']/df_test.loc[i,'Close'] - 1) * 100
    
for i in range(0,754):
    df_test.loc[i,'percentage 2 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'])/df_test.loc[i,'Close'] - 1) * 100
    
for i in range(0,753):
    df_test.loc[i,'percentage 3 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'])/df_test.loc[i,'Close'] - 1) * 100
    
for i in range(0,752):
    df_test.loc[i,'percentage 4 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'],df_test.loc[i+4,'Close'])/df_test.loc[i,'Close'] - 1) * 100
    
for i in range(0,751):
    df_test.loc[i,'percentage 5 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'],df_test.loc[i+4,'Close'],df_test.loc[i+5,'Close'])/df_test.loc[i,'Close'] - 1) * 100

In [23]:
df_test

,Time,Open,Close,volumelag,rsilag,fastKlag,fastDlag,ADlag,OBVlag,MA5lag,MA15lag,day5Returnlag,day15Returnlag,PROClag,percentage 1 day,percentage 2 day,percentage 3 day,percentage 4 day,percentage 5 day
0,Day1,20.6178,20.2864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.391888,0.391888,0.391888,0.391888,0.391888
1,Day2,20.3924,20.3659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.366991,-1.366991,-1.366991,-1.366991,-1.366991
2,Day3,20.2864,20.0875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.528189,-0.528189,-0.528189,-0.528189,-0.528189
3,Day4,20.0742,19.9814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.597055,-0.597055,-0.597055,-0.597055,-0.597055
4,Day5,19.9549,19.8621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,Day752,29.7170,29.8009,27239472.0,55.554178,0.749984,0.680560,0.636216,1.771986e+09,29.39168,29.090940,2.546318,2.963086,0.849919,-1.688204,-0.844270,-0.844270,-0.450322,0.000000
752,Day753,29.7338,29.2978,35167648.0,56.693146,0.802100,0.715283,0.110964,1.807154e+09,29.55604,29.153547,2.185258,2.776255,0.281932,0.858426,0.858426,1.259139,0.000000,0.000000
753,Day754,29.3313,29.5493,34585208.0,48.643407,0.489596,0.680560,-0.870744,1.772568e+09,29.58288,29.173673,-1.131839,0.517722,-1.702617,-0.397302,0.397302,0.000000,0.000000,0.000000
754,Day755,29.3816,29.4319,19086854.0,52.290326,0.645817,0.645837,0.699553,1.791655e+09,29.56610,29.200500,0.284400,2.561139,0.854763,0.797774,0.000000,0.000000,0.000000,0.000000
755,Day756,29.3649,29.6667,19094004.0,50.488002,0.523228,0.552880,-0.000373,1.772561e+09,29.55938,29.241867,-0.959384,2.272577,-0.398093,0.000000,0.000000,0.000000,0.000000,0.000000

In [24]:
df_test['label1'] = np.zeros(756)
df_test['label2'] = np.zeros(756)
df_test['label3'] = np.zeros(756)
df_test['label4'] = np.zeros(756)
df_test['label5'] = np.zeros(756)

In [25]:
df_test.label1 = df_test['percentage 1 day'] >=2
df_test.label2 = df_test['percentage 2 day'] >=2
df_test.label3 = df_test['percentage 3 day'] >=2
df_test.label4 = df_test['percentage 4 day'] >=2
df_test.label5 = df_test['percentage 5 day'] >=2

In [29]:
df_test.loc[df_test['percentage 1 day'] >=2,'label1'] = 1
df_test.loc[df_test['percentage 2 day'] >=2,'label2'] = 1
df_test.loc[df_test['percentage 3 day'] >=2,'label3'] = 1
df_test.loc[df_test['percentage 4 day'] >=2,'label4'] = 1
df_test.loc[df_test['percentage 5 day'] >=2,'label5'] = 1
df_test.loc[df_test['percentage 1 day'] <2,'label1'] = 0
df_test.loc[df_test['percentage 2 day'] <2,'label2'] = 0
df_test.loc[df_test['percentage 3 day'] <2,'label3'] = 0
df_test.loc[df_test['percentage 4 day'] <2,'label4'] = 0
df_test.loc[df_test['percentage 5 day'] <2,'label5'] = 0

In [31]:
df_test.loc[df_test['percentage 1 day'] <2,'label1'] = 0
df_test.loc[df_test['percentage 2 day'] <2,'label2'] = 0
df_test.loc[df_test['percentage 3 day'] <2,'label3'] = 0
df_test.loc[df_test['percentage 4 day'] <2,'label4'] = 0
df_test.loc[df_test['percentage 5 day'] <2,'label5'] = 0

In [37]:
col = ['Open',
 'volumelag',
 'rsilag',
 'fastKlag',
 'fastDlag',
 'ADlag',
 'OBVlag',
 'MA5lag',
 'MA15lag',
 'day5Returnlag',
 'day15Returnlag',
 'PROClag']

In [40]:
df_test.head(30)

,Time,Open,Close,volumelag,rsilag,fastKlag,fastDlag,ADlag,OBVlag,MA5lag,...,percentage 1 day,percentage 2 day,percentage 3 day,percentage 4 day,percentage 5 day,label1,label2,label3,label4,label5
0,Day1,20.6178,20.2864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.391888,0.391888,0.391888,0.391888,0.391888,0,0,0,0,0
1,Day2,20.3924,20.3659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.366991,-1.366991,-1.366991,-1.366991,-1.366991,0,0,0,0,0
2,Day3,20.2864,20.0875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.528189,-0.528189,-0.528189,-0.528189,-0.528189,0,0,0,0,0
3,Day4,20.0742,19.9814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.597055,-0.597055,-0.597055,-0.597055,-0.597055,0,0,0,0,0
4,Day5,19.9549,19.8621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.000000,0,0,0,0,0
5,Day6,19.7825,19.8621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.601145,-0.200382,-0.200382,-0.200382,-0.133420,0,0,0,0,0
6,Day7,19.8886,19.7427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.403187,0.403187,0.403187,0.470554,0.739007,0,0,0,0,0
7,Day8,19.6367,19.8223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.267376,-0.133688,0.067096,0.334472,0.334472,0,0,0,0,0
8,Day9,19.8356,19.7693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.134046,0.335368,0.603461,0.603461,0.871553,0,0,0,0,0
9,Day10,19.7162,19.7958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.201053,0.468786,0.468786,0.736520,1.540226,0,0,0,0,0
10,Day11,19.8090,19.8356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.267196,0.267196,0.534393,1.336486,1.336486,0,0,0,0,0
11,Day12,19.8223,19.8886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.533471,0.266484,1.066440,1.066440,1.066440,0,0,0,0,0
12,Day13,19.8886,19.7825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.804246,1.608492,1.608492,1.608492,1.608492,0,0,0,0,0
13,Day14,19.7560,19.9416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.797830,0.797830,0.797830,0.797830,0.797830,0,0,0,0,0
14,Day15,20.0212,20.1007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.263672,-0.263672,-0.263672,-0.131836,-0.131836,0,0,0,0,0
15,Day16,20.1405,20.0477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.859949,0.000000,0.132185,0.132185,0.132185,0,0,0,0,0
16,Day17,20.0610,19.8753,14753200.0,41.546629,0.450712,0.393310,-0.444491,21737400.0,19.95222,...,0.867408,1.000740,1.000740,1.000740,1.000740,0,0,0,0,0
17,Day18,19.8753,20.0477,13919000.0,36.468773,0.379940,0.445887,-0.889355,7818400.0,19.94956,...,0.132185,0.132185,0.132185,0.132185,0.132185,0,0,0,0,0
18,Day19,20.0079,20.0742,9662200.0,43.858272,0.639970,0.490207,0.899698,17480600.0,20.00260,...,-0.132010,-0.132010,-0.132010,-0.132010,-0.132010,0,0,0,0,0
19,Day20,19.7825,20.0477,15533500.0,44.918806,0.629609,0.549839,-0.600000,33014100.0,20.02912,...,-0.397053,-0.397053,-0.397053,-0.397053,-0.397053,0,0,0,0,0
20,Day21,19.9947,19.9681,19682600.0,44.023224,0.592598,0.620726,0.818099,13331500.0,20.01852,...,-1.062194,-0.730165,-0.464741,-0.464741,1.128800,0,0,0,0,0
21,Day22,19.8356,19.7560,7079300.0,41.355955,0.481425,0.567877,0.473601,6252200.0,20.00260,...,0.335594,0.603867,0.603867,2.214517,2.281838,0,0,0,1,1
22,Day23,19.7693,19.8223,7276100.0,35.230767,0.185196,0.419739,-0.444491,-1023900.0,19.97874,...,0.267376,0.267376,1.872638,1.939735,1.939735,0,0,0,0,0
23,Day24,19.8223,19.8753,5456800.0,38.306700,0.277793,0.314804,0.272977,4432900.0,19.93366,...,0.000000,1.600982,1.667899,1.667899,1.667899,0,0,0,0,0
24,Day25,19.8886,19.8753,6118500.0,40.729909,0.326904,0.263297,0.428110,10551400.0,19.89388,...,1.600982,1.667899,1.667899,1.667899,1.667899,0,0,0,0,0
25,Day26,19.9814,20.1935,4551900.0,40.729909,0.326904,0.310533,-0.091158,10551400.0,19.85940,...,0.065863,0.065863,0.065863,0.065863,0.065863,0,0,0,0,0
26,Day27,20.1935,20.2068,19484600.0,53.458649,0.788397,0.480735,0.599879,30036000.0,19.90448,...,-1.640537,-1.574717,-1.574717,-0.393432,-0.262288,0,0,0,0,0
27,Day28,20.1538,19.8753,9248700.0,53.904251,0.807687,0.640996,-0.124941,39284700.0,19.99464,...,0.066917,0.066917,1.267905,1.401237,2.801970,0,0,0,0,1
28,Day29,19.8753,19.8886,14758900.0,42.883429,0.326904,0.640996,-1.000000,24525800.0,20.00524,...,-0.466599,1.200185,1.333427,2.733224,3.600052,0,0,0,1,1
29,Day30,19.9284,19.7958,6667700.0,43.383563,0.346193,0.493594,0.499686,31193500.0,20.00790,...,1.674598,1.808464,3.214823,4.085715,4.085715,0,0,1,1,1

# Classifier

In [ ]:
# Building different classifer on each stock.
# Choosing the best model from a bunch of classifiers with different hyper parameters.
# Running the applications on a 20-day interval, which means picking a new model for each stock every 20 days.

In [42]:
training_set = df_test.loc[16:503]

In [43]:
test_set = df_test.loc[504:]

In [299]:
df_test = 0

In [304]:
params = {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}
knn = KNeighborsClassifier()
model = GridSearchCV(knn, params, cv=5)
error = pd.DataFrame(columns=['label5 count','fr','fpr','fnr'],index=fns)

for t in fns:
    start = time.time()
    df = pd.DataFrame(columns = ['preds', 'label5', 'check', 'check2'])
    df.iloc[:,0] = np.zeros(253)
    df.iloc[:,1] = np.zeros(253)
    df.iloc[:,2] = np.zeros(253)
    df.iloc[:,3] = np.zeros(253)
    df.index = range(503,756)
    df_test = c[t].copy()
    
    for i in range(0,755):
        df_test.loc[i,'percentage 1 day'] = (df_test.loc[i+1,'Close']/df_test.loc[i,'Close'] - 1) * 100

    for i in range(0,754):
        df_test.loc[i,'percentage 2 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'])/df_test.loc[i,'Close'] - 1) * 100

    for i in range(0,753):
        df_test.loc[i,'percentage 3 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'])/df_test.loc[i,'Close'] - 1) * 100

    for i in range(0,752):
        df_test.loc[i,'percentage 4 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'],df_test.loc[i+4,'Close'])/df_test.loc[i,'Close'] - 1) * 100

    for i in range(0,751):
        df_test.loc[i,'percentage 5 day'] = (max(df_test.loc[i+1,'Close'],df_test.loc[i+2,'Close'],df_test.loc[i+3,'Close'],df_test.loc[i+4,'Close'],df_test.loc[i+5,'Close'])/df_test.loc[i,'Close'] - 1) * 100

    i=0
    
    
    df_test['label1'] = np.zeros(756)
    df_test['label2'] = np.zeros(756)
    df_test['label3'] = np.zeros(756)
    df_test['label4'] = np.zeros(756)
    df_test['label5'] = np.zeros(756)
    
    df_test.loc[df_test['percentage 1 day'] >=2,'label1'] = 1
    df_test.loc[df_test['percentage 2 day'] >=2,'label2'] = 1
    df_test.loc[df_test['percentage 3 day'] >=2,'label3'] = 1
    df_test.loc[df_test['percentage 4 day'] >=2,'label4'] = 1
    df_test.loc[df_test['percentage 5 day'] >=2,'label5'] = 1
    df_test.loc[df_test['percentage 1 day'] <2,'label1'] = 0
    df_test.loc[df_test['percentage 2 day'] <2,'label2'] = 0
    df_test.loc[df_test['percentage 3 day'] <2,'label3'] = 0
    df_test.loc[df_test['percentage 4 day'] <2,'label4'] = 0
    df_test.loc[df_test['percentage 5 day'] <2,'label5'] = 0


    
    
    for i in range(503,754,20):
        if i < 740:
            
            lb = i-100
            ub = i+19
            temp = df_test.loc[lb:ub].copy()
            full = temp[col]
            train_x = full.head(100)
            test_x = full.tail(20)
            train_x_scaled = scaler.fit_transform(train_x)
            test_x_scaled = scaler.fit_transform(test_x)
            train_y = temp.label5.head(100)
            test_y = temp.label5.tail(20)
            model.fit(train_x_scaled, train_y)
            preds = model.predict(test_x_scaled)
            df.loc[range(i,i+20),'preds'] = preds
            df.loc[range(i,i+20),'label5'] = test_y
            df.loc[range(i,i+20),'check'] = df.loc[range(i,i+20),'preds'] == df.loc[range(i,i+20),'label5']
            
        else:
            
            lb = i-100
            ub = i+12
            temp = df_test.loc[lb:ub].copy()
            full = temp[col]
            train_x = full.head(100)
            test_x = full.tail(13)
            train_x_scaled = scaler.fit_transform(train_x)
            test_x_scaled = scaler.fit_transform(test_x)
            train_y = temp.label5.head(100)
            test_y = temp.label5.tail(13)
            model.fit(train_x_scaled, train_y)
            preds = model.predict(test_x_scaled)
            df.loc[range(i,756),'preds'] = preds
            df.loc[range(i,756),'label5'] = test_y
            df.loc[range(i,756),'check'] = df.loc[range(i,756),'preds'] == df.loc[range(i,756),'label5']
            


    for i in df.index:
        if df.loc[i,'preds'] == df.loc[i,'label5']:
            df.loc[i,'check2'] = 'True'
        elif df.loc[i,'preds'] > df.loc[i,'label5']:
            df.loc[i,'check2'] = 'False Positive'
        elif df.loc[i,'preds'] < df.loc[i,'label5']:
            df.loc[i,'check2'] = 'False Negative'
            
    label_count = df.sum()[1]
    false_N_rate = sum(df.check2 == 'False Negative') / sum(df.label5)
    false_P_rate = sum(df.check2 == 'False Positive') / (len(df)-sum(df.label5))
    false_rate = 1-(df.sum()[2]/len(df))
    error.loc[t,'label5 count'] = label_count
    error.loc[t,'fr'] = false_rate
    error.loc[t,'fpr'] = false_P_rate
    error.loc[t,'fnr'] = false_N_rate
    print(time.time()-start)

3.587533950805664
3.328497886657715
3.3153152465820312

/Users/j/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)

3.431617021560669
3.5600740909576416
3.3735709190368652
3.3640499114990234
3.3482789993286133
3.373757839202881
3.4754910469055176
3.65799880027771
3.3752200603485107
3.3908629417419434
3.374613046646118
3.520045042037964
3.874505043029785
3.6686360836029053
3.629801034927368
3.7458338737487793
3.7719850540161133
3.6536810398101807
3.8017799854278564
3.632416009902954
3.7159619331359863
3.74263596534729
3.9191977977752686
3.49216890335083
3.7474639415740967
3.448984146118164
3.552014112472534
3.369987726211548
3.3625752925872803
3.3745641708374023
3.3553543090820312
3.3843178749084473
3.3662028312683105
3.3718819618225098
3.363114833831787
3.3582100868225098
3.3923709392547607
3.6224422454833984
3.402029037475586
3.5147857666015625
3.788818120956421
3.953691244125366
3.820382833480835
3.779723882675171
3.57346510887146
3.5350301265716553
3.476961135864258

In [318]:
error['label5 count'] = error['label5 count'].astype(float)
error['fr'] = error['fr'].astype(float)
error['fpr'] = error['fpr'].astype(float)
error['fnr'] = error['fnr'].astype(float)

In [320]:
error.describe()

       label5 count         fr        fpr        fnr
count     50.000000  50.000000  50.000000  50.000000
mean      94.000000   0.369881   0.293706   0.600815
std       29.712225   0.088685   0.165920   0.197411
min       32.000000   0.166008   0.019048   0.242857
25%       70.250000   0.311265   0.172892   0.445071
50%       97.500000   0.399209   0.290397   0.573586
75%      118.750000   0.426877   0.409788   0.767484
max      143.000000   0.505929   0.699115   0.976744

In [305]:
error

         label5 count        fr        fpr       fnr
SH601288           43  0.181818  0.0190476  0.976744
SH601088           80  0.332016   0.248555    0.5125
SH600585          130  0.462451   0.528455       0.4
SH601857           32  0.205534   0.104072   0.90625
SH600036          119  0.418972   0.470149  0.361345
SH601328           53  0.209486      0.065  0.754717
SH600999           95  0.399209   0.291139  0.578947
SH600637           93  0.383399    0.29375  0.537634
SH600958          100   0.41502   0.267974      0.64
SH601688          109  0.422925      0.375  0.486239
SH600583          118  0.482213   0.437037  0.533898
SH600018          120  0.426877   0.413534  0.441667
SH600030          121   0.41502   0.424242  0.404959
SH600150          140   0.44664   0.699115  0.242857
SH601766           60  0.249012  0.0829016  0.783333
SH600518          123  0.505929   0.553846  0.455285
SH600256           83  0.383399   0.241176  0.674699
SH600519          143  0.391304   0.572727  0.251748
SH600690          122  0.418972   0.328244  0.516393
SH600109          111  0.426877   0.457746  0.387387
SH601398           59  0.252964  0.0515464  0.915254
SH601818           92  0.403162   0.192547  0.771739
SH600050          101   0.41502   0.335526  0.534653
SH601006           58  0.245059  0.0717949  0.827586
SH601628          133  0.379447   0.391667  0.368421
SH601166          104  0.438735   0.342282  0.576923
SH601601          130   0.44664   0.528455  0.369231
SH601988           39  0.166008  0.0514019  0.794872
SH600089           63   0.29249   0.215789   0.52381
SH601989          115  0.399209   0.398551       0.4
SH601169           51  0.245059  0.0841584  0.882353
SH601800           80  0.351779   0.138728    0.8125
SH600048          125  0.482213   0.492188     0.472
SH600104          114  0.438735   0.352518   0.54386
SH601186           95  0.403162   0.240506  0.673684
SH601390           66  0.304348  0.0962567  0.893939
SH600893           85  0.395257    0.27381  0.635294
SH600887          111   0.43083   0.422535  0.441441
SH600111          108  0.442688   0.289655  0.648148
SH601998           82  0.407115   0.169591  0.902439
SH600015           49   0.26087   0.107843  0.897959
SH600000           85  0.387352    0.22619  0.705882
SH600028           67  0.304348   0.182796  0.641791
SH601901          112  0.422925   0.333333  0.535714
SH600406          115  0.347826   0.362319  0.330435
SH600837          121  0.478261   0.393939  0.570248
SH600016           41  0.173913  0.0283019  0.926829
SH601668           93  0.383399       0.25  0.612903
SH601318          126  0.434783   0.543307  0.325397
SH600010           85  0.383399   0.244048  0.658824

In [337]:
df.head(20)

     preds  label1  check          check2
503    0.0     0.0   True            True
504    0.0     0.0   True            True
505    0.0     0.0   True            True
506    0.0     0.0   True            True
507    0.0     0.0   True            True
508    0.0     0.0   True            True
509    0.0     0.0   True            True
510    0.0     0.0   True            True
511    0.0     0.0   True            True
512    0.0     0.0   True            True
513    0.0     0.0   True            True
514    0.0     0.0   True            True
515    0.0     0.0   True            True
516    0.0     1.0  False  False Negative
517    0.0     0.0   True            True
518    0.0     0.0   True            True
519    0.0     0.0   True            True
520    0.0     0.0   True            True
521    0.0     0.0   True            True
522    0.0     0.0   True            True